name: Publish Book

on:
  schedule:
    - cron: "0 12 * * *" # "12:00 UTC" - https://crontab.guru/#0_12_*_*_*e
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    name: Publish Book
    runs-on: macos-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        brew update
        brew install pandoc
        brew install --cask basictex
        eval "$(/usr/libexec/path_helper)"

    - name: Download NIPs
      run: |
        make setup
        cd nips/
        git log -n1
        cd ../

    - name: Create books
      run: |
        export PATH="/Library/TeX/texbin:$PATH"
        make all

    - name: Commit and Push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "support@github.com"

        git add -A nostr-book.* ./include/git.md
        git commit -m "chore: automated publishing"
        git push origin master
